problem_type: MIMO
dummy_qam: 2
dummy_snr: 8
dummy_spacing: 1.0
dummy_user_num: 24
dummy_ant_num: 24
dummy_case_num: 2
initialization_seed: 42
seed: 100
dummy_seed: 42
nb_trials: 2
nb_runs: 2
dummy_creator: true
use_ZF: true
nb_flipping: 1
logfile_discrimination: "chip_experiment_model6"
