# channel mapping file for the LUBIT measurement board v1.0

# dac's
#  mapping:
#   dac1: bus0
#   dac2: bus1
#  channels:
#   0-3: first dac
#   4-7: second (daisy-chained) dac
#  max/min/nom: voltages (to check bounds and to set standard values)
class channel_map_class:
	def __init__(self):
		self.dac = {
			"AV1": {
				"channel": 3,
				"bus": 0,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV2": {
				"channel": 2,
				"bus": 0,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV3": {
				"channel": 0,
				"bus": 0,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV4": {
				"channel": 1,
				"bus": 0,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV5": {
				"channel": 7,
				"bus": 0,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV6": {
				"channel": 6,
				"bus": 0,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV7": {
				"channel": 4,
				"bus": 0,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV8": {
				"channel": 5,
				"bus": 0,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV9": {
				"channel": 3,
				"bus": 1,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV10": {
				"channel": 2,
				"bus": 1,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV11": {
				"channel": 0,
				"bus": 1,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV12": {
				"channel": 1,
				"bus": 1,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV13": {
				"channel": 7,
				"bus": 1,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV14": {
				"channel": 6,
				"bus": 1,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV15": {
				"channel": 4,
				"bus": 1,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"AV16": {
				"channel": 5,
				"bus": 1,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV1": {
				"channel": 3,
				"bus": 2,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV2": {
				"channel": 2,
				"bus": 2,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV3": {
				"channel": 0,
				"bus": 2,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV4": {
				"channel": 1,
				"bus": 2,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV5": {
				"channel": 7,
				"bus": 2,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV6": {
				"channel": 6,
				"bus": 2,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV7": {
				"channel": 4,
				"bus": 2,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV8": {
				"channel": 5,
				"bus": 2,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV9": {
				"channel": 3,
				"bus": 3,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV10": {
				"channel": 2,
				"bus": 3,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV11": {
				"channel": 0,
				"bus": 3,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV12": {
				"channel": 1,
				"bus": 3,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV13": {
				"channel": 7,
				"bus": 3,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV14": {
				"channel": 6,
				"bus": 3,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV15": {
				"channel": 4,
				"bus": 3,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
			"BV16": {
				"channel": 5,
				"bus": 3,
				"max": 0.5,
				"min": 0,
				"nom": 0.2,
			},
		}

		#adc's
		#  mapping:
		#   adc0: A board V1-8 : bus1
		#   adc1: A board V9-16: bus0
		#   adc2: B board V1-8 : bus3
		#   adc3: B board V9-16: bus2
		self.adc = {
			"AV1": {
				"channel": 0,
				"bus": 1,
				"type": "current",
				"name": "AV1",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV2": {
				"channel": 3,
				"bus": 1,
				"type": "current",
				"name": "AV2",
				"midpoint_volt": 1.4,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV3": {
				"channel": 2,
				"bus": 1,
				"type": "current",
				"name": "AV3",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV4": {
				"channel": 1,
				"bus": 1,
				"type": "current",
				"name": "AV4",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV5": {
				"channel": 4,
				"bus": 1,
				"type": "current",
				"name": "AV5",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV6": {
				"channel": 7,
				"bus": 1,
				"type": "current",
				"name": "AV6",
				"midpoint_volt": 1.4,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV7": {
				"channel": 6,
				"bus": 1,
				"type": "current",
				"name": "AV7",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV8": {
				"channel": 5,
				"bus": 1,
				"type": "current",
				"name": "AV8",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV9": {
				"channel": 0,
				"bus": 0,
				"type": "current",
				"name": "AV9",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV10": {
				"channel": 3,
				"bus": 0,
				"type": "current",
				"name": "AV10",
				"midpoint_volt": 1.4,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV11": {
				"channel": 2,
				"bus": 0,
				"type": "current",
				"name": "AV11",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV12": {
				"channel": 1,
				"bus": 0,
				"type": "current",
				"name": "AV12",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV13": {
				"channel": 4,
				"bus": 0,
				"type": "current",
				"name": "AV13",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV14": {
				"channel": 7,
				"bus": 0,
				"type": "current",
				"name": "AV14",
				"midpoint_volt": 1.4,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV15": {
				"channel": 6,
				"bus": 0,
				"type": "current",
				"name": "AV15",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"AV16": {
				"channel": 5,
				"bus": 0,
				"type": "current",
				"name": "AV16",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV1": {
				"channel": 0,
				"bus": 3,
				"type": "current",
				"name": "BV1",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV2": {
				"channel": 3,
				"bus": 3,
				"type": "current",
				"name": "BV2",
				"midpoint_volt": 1.4,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV3": {
				"channel": 2,
				"bus": 3,
				"type": "current",
				"name": "BV3",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV4": {
				"channel": 1,
				"bus": 3,
				"type": "current",
				"name": "BV4",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV5": {
				"channel": 4,
				"bus": 3,
				"type": "current",
				"name": "BV5",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV6": {
				"channel": 7,
				"bus": 3,
				"type": "current",
				"name": "BV6",
				"midpoint_volt": 1.4,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV7": {
				"channel": 6,
				"bus": 3,
				"type": "current",
				"name": "BV7",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV8": {
				"channel": 5,
				"bus": 3,
				"type": "current",
				"name": "BV8",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV9": {
				"channel": 0,
				"bus": 2,
				"type": "current",
				"name": "BV9",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV10": {
				"channel": 3,
				"bus": 2,
				"type": "current",
				"name": "BV10",
				"midpoint_volt": 1.4,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV11": {
				"channel": 2,
				"bus": 2,
				"type": "current",
				"name": "BV11",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV12": {
				"channel": 1,
				"bus": 2,
				"type": "current",
				"name": "BV12",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV13": {
				"channel": 4,
				"bus": 2,
				"type": "current",
				"name": "BV13",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV14": {
				"channel": 7,
				"bus": 2,
				"type": "current",
				"name": "BV14",
				"midpoint_volt": 1.4,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV15": {
				"channel": 6,
				"bus": 2,
				"type": "current",
				"name": "BV15",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			},
			"BV16": {
				"channel": 5,
				"bus": 2,
				"type": "current",
				"name": "BV16",
				"midpoint_volt": 0.9,
				"gain_ina": 1000,
				"r_shunt_ohm": 100,
			}
		}
