ctrl_interface=/var/run/wpa_supplicant
network={
key_mgmt=IEEE8021X
eap=PEAP
identity="<username_will_be_set_by_script>@esat.kuleuven.be"
password=hash:<pwhash_will_be_set_by_script>
phase2="auth=MSCHAPV2"
}
